apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wish-cart-efs-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "wish-cart-efs-sc"
  resources:
    requests:
      storage: 5Gi