apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: ClusterIP
  ports:
    - name: amqp
      targetPort: 5672
      port: 5672
    - name: management
      targetPort: 15672
      port: 15672
  selector:
    app: rabbitmq-service
    profile: dev