apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
  namespace: prod
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
  selector:
    app: zipkin-service
