apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-standalone-pv
spec:
  volumeMode: Filesystem
  storageClassName: gp2
  capacity:
    storage: 10Gi # 볼륨의 크기
  awsElasticBlockStore:
    volumeID: vol-072aa9b646d90fc51
  accessModes:
    - ReadWriteOnce # 하나의 Pod에 마운트
  persistentVolumeReclaimPolicy: Retain