apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-standalone-pvc
  namespace: prod
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce # 하나의 노드가 Read/Write 가능하도록 마운트
  resources:
    requests:
      storage: 10Gi # 볼륨 크기가 최소 5Gi인 퍼시스턴트 볼륨과 연결