apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-deployment
  labels:
    app: promotion-service
    profile: dev
spec:
  # Deployment Spec
  selector:
    # Match mapping pod's label
    matchLabels:
      app: promotion-service
      profile: dev
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  # Pod Spec
  template:
    metadata:
      name: promotion-pod
      # Set pod's label
      labels:
        app: promotion-service
        profile: dev
    spec:
      containers:
        - name: promotion-service
          image: akak640/dailyon-promotion-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8084
          imagePullPolicy: Always
        - name: mongo
          image: mongo:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "11111111"
            - name: MONGO_INITDB_DATABASE
              value: promotion-service
        - name: dynamodb
          image: "amazon/dynamodb-local:latest"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"