apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: dev
  labels:
    app: kafka-service
spec:
  # Deployment Spec
  selector:
    # Match mapping pod's label
    matchLabels:
      app: kafka-service
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  # Pod Spec
  template:
    metadata:
      name: kafka-pod
      # Set pod's label
      labels:
        app: kafka-service
    spec:
      containers:
        # - name: kafka-service
        #   image: wurstmeister/kafka
        #   resources:
        #     requests:
        #       memory: "512Mi"
        #       cpu: "1000m"
        #     limits:
        #       memory: "768Mi"
        #       cpu: "1500m"
        #   ports:
        #     - containerPort: 9092
        #   env:
        #     - name: KAFKA_ADVERTISED_HOST_NAME
        #       value: kafka-service
        #     - name: KAFKA_CREATE_TOPICS
        #       value: "create-order:1:1,create-project:1:1,create-maker:1:1,auth-project:1:1,create-member:1:1"
        #     - name: KAFKA_ZOOKEEPER_CONNECT
        #       value: zookeeper-service:2181
        - name: kafka1
          image: confluentinc/cp-kafka
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "768Mi"
              cpu: "1500m"
          ports:
          - containerPort: 9092
          env:
          - name: KAFKA_NODE_ID
            value: "1"
          - name: KAFKA_CONTROLLER_LISTENER_NAMES
            value: 'CONTROLLER'
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
          # Kafka가 서비스를 제공하는 주소
          - name: KAFKA_LISTENERS
            value: 'INTERNAL://localhost:29092,CONTROLLER://localhost:29093,EXTERNAL://0.0.0.0:9092'
          # Client에게 Metadata와 함께 반환할 서버 주소
          - name: KAFKA_ADVERTISED_LISTENERS
            value: 'INTERNAL://localhost:29092,EXTERNAL://localhost:9092'
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: 'INTERNAL'
          - name: KAFKA_CONTROLLER_QUORUM_VOTERS
            value: '1@kafka-service:29093'
          - name: KAFKA_PROCESS_ROLES
            value: 'broker,controller'
          - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            value: "0"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "3"
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: "3"
          - name: CLUSTER_ID
            value: 'ciWo7IWazngRchmPES6q5A=='
          - name: KAFKA_LOG_DIRS
            value: '/var/lib/kafka/data'
