apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka-service
    profile: dev
spec:
  # Deployment Spec
  selector:
    # Match mapping pod's label
    matchLabels:
      app: kafka-service
      profile: dev
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  # Pod Spec
  template:
    metadata:
      name: kafka-pod
      # Set pod's label
      labels:
        app: kafka-service
        profile: dev
    spec:
      containers:
        - name: kafka-service
          image: wurstmeister/kafka
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "768Mi"
              cpu: "1500m"
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service
            - name: KAFKA_CREATE_TOPICS
              value: "create-order:1:1,create-project:1:1,create-maker:1:1,auth-project:1:1,create-member:1:1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181