apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - name: external
      targetPort: 9092
      port: 9092
    - name: controller
      targetPort: 29093
      port: 29093
  selector:
    app: kafka-service