apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - name: zookeeper-service
      targetPort: 2181
      port: 2181
  selector:
    app: zookeeper-service