apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  namespace: dev
  labels:
    app: apigateway-service
spec:
  # Deployment Spec
  selector:
    # Match mapping pod's label
    matchLabels:
      app: apigateway-service
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  # Pod Spec
  template:
    metadata:
      name: apigateway-pod
      # Set pod's label
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway-service
          image: akak640/dailyon-apigateway-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "384Mi"
              cpu: "250m"
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          # 애플리케이션이 시작된 뒤 초기화 작업이 마무리되어 준비되었는지 검사
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 2
      affinity:
        nodeAffinity:
          # Pod이 존재하지 않다가 처음으로 만들어지는 상태, 이미 실행중인데 nodeSelector가 node에서 제거된다면 계속 실행
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                    - App
                - key: size
                  operator: In
                  values:
                    - Large
                    - Medium