apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30002
  selector:
    app: apigateway-service
    profile: dev
