apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: dev
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: apigateway-service