apiVersion: v1
kind: Service
metadata:
  name: auction-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - targetPort: 8083
      port: 8083
  selector:
    app: auction-service
    profile: dev
