apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - name: client
      targetPort: 6379
      port: 6379
    - name: gossip
      port: 16379
      targetPort: 16379
  selector:
    app: redis-cluster