apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-db-statefulset
  namespace: prod
  labels:
    app: payment-db-service
spec:
  serviceName: payment-db-service
  selector:
    matchLabels:
      app: payment-db-service
  replicas: 1
  template:
    metadata:
      name: payment-db-pod
      labels:
        app: payment-db-service
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.34
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "11111111"
            - name: MYSQL_DATABASE
              value: payment-service
            - name: LC_ALL
              value: C.UTF-8
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
            - name: payment-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: payment-efs-pv
              mountPath: /var/lib/mysql
          imagePullPolicy: IfNotPresent
          # 애플리케이션이 시작된 뒤 초기화 작업이 마무리되어 준비되었는지 검사
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 20
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
        - name: payment-initdb
          configMap:
            name: payment-initdb-config
        - name: payment-efs-pv
          persistentVolumeClaim:
            claimName: payment-efs-pvc
      # SIGTERM을 받아도 바로 종료되지 않고 180초 뒤에 종료
      terminationGracePeriodSeconds: 120
      restartPolicy: Always
      affinity:
        nodeAffinity:
          # Pod이 존재하지 않다가 처음으로 만들어지는 상태, 이미 실행중인데 nodeSelector가 node에서 제거된다면 계속 실행
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - Database
                  - key: size
                    operator: In
                    values:
                      - Large
                      - Medium
