apiVersion: v1
kind: ConfigMap
metadata:
  name: product-initdb-config
  namespace: dev
data:
  initdb.sql: |
    create table brand (
      id bigint not null auto_increment,
      created_at datetime(6),
      updated_at datetime(6),
      is_deleted BOOLEAN default false not null,
      name varchar(255) not null,
      primary key (id)
    ) engine=InnoDB;
        
    create table category (
      id bigint not null auto_increment,
      created_at datetime(6),
      updated_at datetime(6),
      is_deleted BOOLEAN default false not null,
      name varchar(255) not null,
      master_category_id bigint,
      primary key (id)
    ) engine=InnoDB;
        
    create table describe_image (
      id bigint not null auto_increment,
      img_url varchar(255) not null,
      product_id bigint,
      primary key (id)
    ) engine=InnoDB;
        
    create table product (
      id bigint not null auto_increment,
      created_at datetime(6),
      updated_at datetime(6),
      code varchar(255) not null,
      is_deleted BOOLEAN default false not null,
      gender varchar(255) not null,
      img_url varchar(255) not null,
      name varchar(255) not null,
      price integer not null,
      type varchar(255) not null,
      brand_id bigint,
      category_id bigint,
      primary key (id)
    ) engine=InnoDB;
        
    create table product_size (
      id bigint not null auto_increment,
      created_at datetime(6),
      updated_at datetime(6),
      is_deleted BOOLEAN default false not null,
      name varchar(255) not null,
      category_id bigint,
      primary key (id)
    ) engine=InnoDB;
        
    create table product_stock (
      product_id bigint not null,
      product_size_id bigint not null,
      quantity bigint not null,
      primary key (product_id, product_size_id)
    ) engine=InnoDB;
        
    create table review_aggregate (
      product_id bigint not null,
      avg_rating float not null,
      review_count bigint not null,
      primary key (product_id)
    ) engine=InnoDB;
        
    alter table brand 
      add constraint UK_rdxh7tq2xs66r485cc8dkxt77 unique (name);

    alter table category 
      add constraint UK_46ccwnsi9409t36lurvtyljak unique (name);

    alter table product 
      add constraint UK_h3w5r1mx6d0e5c6um32dgyjej unique (code);
          
    alter table product_size 
      add constraint UKd5mdp3qtp2h1p7vjqp4y8ch88 unique (name, category_id);
          
    alter table category 
      add constraint FKlray2xijqyh4pbmoqv5ytimje 
      foreign key (master_category_id) 
      references category (id);
          
    alter table describe_image 
      add constraint FK7x85hs232jdhahwgj5n5dte85 
      foreign key (product_id) 
      references product (id);
          
    alter table product 
      add constraint FKs6cydsualtsrprvlf2bb3lcam 
      foreign key (brand_id) 
      references brand (id);
          
    alter table product 
      add constraint FK1mtsbur82frn64de7balymq9s 
      foreign key (category_id) 
      references category (id);
          
    alter table product_size 
      add constraint FKg8p8y93lnxirp3a81b51b2aun 
      foreign key (category_id) 
      references category (id);
          
    alter table product_stock 
      add constraint FKlpu1phje1bb3y9ww8k9fut4gh 
      foreign key (product_id) 
      references product (id);
          
    alter table product_stock 
      add constraint FKq59hexicbfe6ke1r1jg162iaj 
      foreign key (product_size_id) 
      references product_size (id);
          
    alter table review_aggregate 
      add constraint FKbn4603xy69cwa185g532d7v05 
      foreign key (product_id) 
      references product (id);
    
    INSERT INTO brand (name, created_at, updated_at)
    VALUES ('Brand1', NOW(), NOW()),
          ('Brand2', NOW(), NOW()),
          ('Brand3', NOW(), NOW()),
          ('Brand4', NOW(), NOW()),
          ('Brand5', NOW(), NOW());

    INSERT INTO category (master_category_id, name, created_at, updated_at)
    VALUES (NULL, 'RootCategory1', NOW(), NOW()),
          (NULL, 'RootCategory2', NOW(), NOW());

    INSERT INTO category (master_category_id, name, created_at, updated_at)
    VALUES (1, 'SubCategory1-1', NOW(), NOW()),
          (1, 'Subcategory1-2', NOW(), NOW()),
          (2, 'Subcategory2-1', NOW(), NOW()),
          (2, 'Subcategory2-2', NOW(), NOW());

    INSERT INTO product_size (category_id, name, created_at, updated_at)
    VALUES (3, 'Size1', NOW(), NOW()),
          (3, 'Size2', NOW(), NOW()),
          (4, 'Size1', NOW(), NOW()),
          (4, 'Size2', NOW(), NOW()),
          (5, 'Size1', NOW(), NOW()),
          (5, 'Size2', NOW(), NOW()),
          (6, 'Size1', NOW(), NOW()),
          (6, 'Size2', NOW(), NOW());

    INSERT INTO product (brand_id, category_id, name, code, img_url, price, gender, type, created_at, updated_at)
    VALUES (1, 3, 'Product1',  'P001', '/product-img/default-product-img.png',  100000, 'COMMON', 'NORMAL', NOW(), NOW()),
          (2, 3, 'Product2',  'P002', '/product-img/default-product-img.png',  150000, 'MALE',   'NORMAL', NOW(), NOW()),
          (3, 3, 'Product3',  'P003', '/product-img/default-product-img.png',  200000, 'FEMALE', 'NORMAL', NOW(), NOW()),
          (4, 4, 'Product4',  'P004', '/product-img/default-product-img.png',  120000, 'COMMON', 'NORMAL', NOW(), NOW()),
          (5, 4, 'Product5',  'P005', '/product-img/default-product-img.png',  180000, 'MALE',   'NORMAL', NOW(), NOW()),
          (1, 4, 'Product6',  'P006', '/product-img/default-product-img.png',  130000, 'FEMALE', 'NORMAL', NOW(), NOW()),
          (2, 5, 'Product7',  'P007', '/product-img/default-product-img.png',  90000,  'COMMON', 'NORMAL', NOW(), NOW()),
          (3, 5, 'Product8',  'P008', '/product-img/default-product-img.png',  160000, 'MALE',   'NORMAL', NOW(), NOW()),
          (4, 6, 'Product9',  'P009', '/product-img/default-product-img.png',  220000, 'FEMALE', 'NORMAL', NOW(), NOW()),
          (5, 6, 'Product10', 'P010', '/product-img/default-product-img.png',  110000, 'COMMON', 'NORMAL', NOW(), NOW());

    INSERT INTO product_stock (product_id, product_size_id, quantity)
    VALUES (1, 1, 50), (2, 2, 30), (3, 3, 40), (4, 4, 25), (5, 5, 35),
          (6, 6, 20), (7, 7, 45), (8, 8, 60), (9, 1, 15), (10, 2, 55),
          (1, 5, 25), (2, 6, 40), (3, 7, 55), (4, 8, 30), (5, 1, 45),
          (6, 2, 20), (7, 3, 35), (8, 4, 50), (9, 5, 25), (10, 6, 40);

    INSERT INTO describe_image (product_id, img_url)
    VALUES (1, 'https://via.placeholder.com/500'),
          (2, 'https://via.placeholder.com/500'),
          (3, 'https://via.placeholder.com/500'),
          (4, 'https://via.placeholder.com/500'),
          (5, 'https://via.placeholder.com/500'),
          (6, 'https://via.placeholder.com/500'),
          (7, 'https://via.placeholder.com/500'),
          (8, 'https://via.placeholder.com/500'),
          (9, 'https://via.placeholder.com/500'),
          (10, 'https://via.placeholder.com/500');

    INSERT INTO review_aggregate (product_id, avg_rating, review_count)
    VALUES (1, 0, 0), (2, 0, 0),
          (3, 0, 0), (4, 0, 0),
          (5, 0, 0), (6, 0, 0),
          (7, 0, 0), (8, 0, 0),
          (9, 0, 0), (10, 0, 0);