apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 30Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-098bde1f1143784a8
  persistentVolumeReclaimPolicy: Retain