apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: prod
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /metrics
  labels:
    name: prometheus-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus-service