apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: dev
  labels:
    app: order-service
spec:
  # Deployment Spec
  selector:
    # Match mapping pod's label
    matchLabels:
      app: order-service
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  # Pod Spec
  template:
    metadata:
      name: order-pod
      # Set pod's label
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: akak640/dailyon-order-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8089
          imagePullPolicy: Always
        - name: mysql
          image: mysql:8.0.34
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "11111111"
            - name: MYSQL_DATABASE
              value: order-service
          volumeMounts:
            - name: order-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: order-initdb
          configMap:
            name: order-initdb-config
        - name: mysql-config
          configMap:
            name: mysql-config
      affinity:
        nodeAffinity:
          # Pod이 존재하지 않다가 처음으로 만들어지는 상태, 이미 실행중인데 nodeSelector가 node에서 제거된다면 계속 실행
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                    - App
                - key: size
                  operator: In
                  values:
                    - Large
                    - Medium