apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - name: external
      targetPort: 8083
      port: 8083
  selector:
    app: kafka-connect-service