apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-standalone-pv
spec:
  volumeMode: Filesystem
  storageClassName: gp2
  capacity:
    storage: 10Gi # 볼륨의 크기
  awsElasticBlockStore:
    volumeID: vol-0033802fc6048030f
  accessModes:
    - ReadWriteOnce # 하나의 Pod에 마운트
  persistentVolumeReclaimPolicy: Retain