apiVersion: v1
kind: Service
metadata:
  name: notification-db-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: notification-db-service
