apiVersion: v1
kind: Service
metadata:
  name: notification-db-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - targetPort: 27017
      port: 27017
  selector:
    app: notification-db-service
