apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-cluster-pv
  namespace: prod
spec:
  volumeMode: Filesystem
  storageClassName: gp2
  capacity:
    storage: 10Gi # 볼륨의 크기
  accessModes:
    - ReadWriteOnce # 하나 Pod에 마운트
  awsElasticBlockStore:
    volumeID: vol-09f5adc7aed56058e
  persistentVolumeReclaimPolicy: Retain