apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-efs-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "auth-efs-sc"
  resources:
    requests:
      storage: 5Gi