apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review-service
    profile: dev
spec:
  # Deployment Spec
  selector:
    # Match mapping pod's label
    matchLabels:
      app: review-service
      profile: dev
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  # Pod Spec
  template:
    metadata:
      name: review-pod
      # Set pod's label
      labels:
        app: review-service
        profile: dev
    spec:
      containers:
        - name: review-service
          image: akak640/dailyon-review-service
          ports:
            - containerPort: 8087
          imagePullPolicy: Always
        - name: mysql
          image: mysql:8.0.34
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "11111111"
            - name: MYSQL_DATABASE
              value: review-service
          volumeMounts:
            - name: review-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: review-initdb
          configMap:
            name: review-initdb-config
        - name: mysql-config
          configMap:
            name: mysql-config