apiVersion: v1
kind: PersistentVolume
metadata:
  name: member-ebs-pv
spec:
  volumeMode: Filesystem
  storageClassName: gp2
  capacity:
    storage: 10Gi # 볼륨의 크기
  accessModes:
    - ReadWriteOnce # 하나의 Pod에 마운트
  awsElasticBlockStore:
    volumeID: vol-01f14f4954c089954
  persistentVolumeReclaimPolicy: Retain