apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deployment
  labels:
    app: member-service
    profile: dev
spec:
  # Deployment Spec
  selector:
    # Match mapping pod's label
    matchLabels:
      app: member-service
      profile: dev
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  # Pod Spec
  template:
    metadata:
      name: member-pod
      # Set pod's label
      labels:
        app: member-service
        profile: dev
    spec:
      containers:
        - name: member-service
          image: akak640/dailyon-member-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
        - name: mysql
          image: mysql:8.0.34
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "11111111"
            - name: MYSQL_DATABASE
              value: member-service
          volumeMounts:
            - name: member-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: member-initdb
          configMap:
            name: member-initdb-config
        - name: mysql-config
          configMap:
            name: mysql-config