apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 8080
      port: 8080
    - name: mysql
      targetPort: 3306
      port: 3306
  selector:
    app: member-service
