apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-cluster-pv
  namespace: prod
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "kafka-cluster-sc"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-06b8f1c59614be87e