apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-cluster-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "kafka-cluster-sc"
  resources:
    requests:
      storage: 30Gi