apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP
  ports:
    - name: kafka-service
      targetPort: 9092
      port: 9092
  selector:
    app: kafka-service
    profile: prod