apiVersion: apps/v1
kind: Deployment
metadata:
  name: sns-deployment
  labels:
    app: sns-service
    profile: dev
spec:
  # Deployment Spec
  selector:
    # Match mapping pod's label
    matchLabels:
      app: sns-service
      profile: dev
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  # Pod Spec
  template:
    metadata:
      name: sns-pod
      # Set pod's label
      labels:
        app: sns-service
        profile: dev
    spec:
      containers:
        - name: sns-service
          image: akak640/dailyon-sns-service
          ports:
            - containerPort: 8088
          imagePullPolicy: Always
        - name: mysql
          image: mysql:8.0.34
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "11111111"
            - name: MYSQL_DATABASE
              value: admin-service
          volumeMounts:
            - name: sns-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
      volumes:
        - name: sns-initdb
          configMap:
            name: sns-initdb-config
        - name: mysql-config
          configMap:
            name: mysql-config