version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 11111111
    expose:
      - 6379
    networks:
      dailyon-network:
networks:
  dailyon-network:
    name: dailyon-network