apiVersion: v1
kind: Service
metadata:
  name: sns-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - name: app
      targetPort: 8088
      port: 8088
    - name: mysql
      targetPort: 3306
      port: 3306
  selector:
    app: sns-service
