apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-efs-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "product-efs-sc"
  resources:
    requests:
      storage: 5Gi